In [1]:
import tensorflow as tf
import requests
import pandas as pd
import numpy as np

import json
import math

2023-09-04 14:51:40.168508: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-04 14:51:55.096487: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-09-04 14:51:55.110312: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-09-04 14:52:24.277440: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-09-04 14:52:24.285247: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-09-04 14:52:24.285318: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

In [2]:
url = "http://vps-40d69db1.vps.ovh.ca:23004/api/ExperimentoPreRedes/proximoExperimentoParaPontuarSintetico"

r = requests.get(url)
j = r.json()
dfExperimento = pd.DataFrame.from_dict(j)
dfExperimento.head()

,nome,nomeArquivoRede,mediaY0,mediaY1,mediaResultadoNeutro,mediaResultadoPositivo,mediaResultadoNegativo,mediaTotal,desvioY0,desvioY1,...,desvioResultadoNegativo,desvioTotal,qtdeY0,qtdeY1,id,amostraDadoSinteticoEntrada1Id,amostraDadoSinteticoEntrada2Id,amostraDadoSinteticoIndice1Id,amostraDadoSinteticoIndice2Id,versaoPreRedeId
0,Inicial1,ExperimentoSintetico_Prometeu_v0_aInicial,0.07524,0.82131,0.13081,0.82131,0.00116,0.29906,0.235101,0.000026,...,0,0.394436,6720,2880,1,1,NaN,None,None,15
1,Experimento1,None,0.07524,0.82131,0.13081,0.82131,0.00116,0.29906,0.235101,0.000026,...,0,0.394436,6720,2880,2,2,3.0,None,None,16