In [1]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

In [2]:
url = "http://vps-40d69db1.vps.ovh.ca:22001/api/CotacaoIntradayMercadoBitcoins/fechamentosPorDiaNum?diaNum=20220211"

In [3]:
r = requests.get(url)
j = r.json()
df = pd.DataFrame.from_dict(j)

In [5]:
df2 = df.set_index('ticker')

In [6]:
df2.head()

            valor                  dataHora
ticker
AAVE    880.30799  2022-02-11T23:59:26.000Z
ACMFT    23.98900  2022-02-11T23:59:26.000Z
ADA       5.79571  2022-02-11T23:59:27.000Z
ALCX    895.00000  2022-02-11T23:59:36.000Z
ALGO      4.99988  2022-02-11T23:59:36.000Z

In [7]:
url1mes = "http://vps-40d69db1.vps.ovh.ca:22001/api/CotacaoIntradayMercadoBitcoins/fechamentosPorDiaNum?diaNum=20220111"

In [8]:
r = requests.get(url1mes)
j = r.json()
df1mes = pd.DataFrame.from_dict(j)

In [9]:
df1mes = df1mes.set_index('ticker')

In [10]:
df1mes.head()

             valor                  dataHora
ticker
AAVE    1221.88987  2022-01-11T23:52:06.000Z
ACMFT     27.49489  2022-01-11T23:52:07.000Z
ADA        6.74975  2022-01-11T23:52:09.000Z
ALGO       8.24995  2022-01-11T23:52:11.000Z
AMFT       7.63989  2022-01-11T23:52:13.000Z

In [13]:
dfmerge = pd.merge(df1mes,df2,how='inner' , left_index=True, right_index=True, suffixes=('_1', '_0'))

In [14]:
dfmerge.head()

,valor_1,dataHora_1,valor_0,dataHora_0
ticker,,,,
AAVE,1221.88987,2022-01-11T23:52:06.000Z,880.30799,2022-02-11T23:59:26.000Z
ACMFT,27.49489,2022-01-11T23:52:07.000Z,23.98900,2022-02-11T23:59:26.000Z
ADA,6.74975,2022-01-11T23:52:09.000Z,5.79571,2022-02-11T23:59:27.000Z
ALGO,8.24995,2022-01-11T23:52:11.000Z,4.99988,2022-02-11T23:59:36.000Z
AMFT,7.63989,2022-01-11T23:52:13.000Z,6.01000,2022-02-11T23:50:43.000Z

In [15]:
dfmerge['lucro'] = dfmerge['valor_0'] - dfmerge['valor_1']

In [16]:
dfmerge.sort_values(by='lucro', ascending=False)

,valor_1,dataHora_1,valor_0,dataHora_0,lucro
ticker,,,,,
PSGFT,83.435840,2022-01-11T23:53:37.000Z,88.560050,2022-02-11T23:56:58.000Z,5.124210
MBSANTOS01,50.000000,2022-01-11T23:53:29.000Z,50.000000,2022-02-11T23:54:36.000Z,0.000000
SHIB,0.000159,2022-01-11T23:53:43.000Z,0.000155,2022-02-11T23:57:37.000Z,-0.000004
ARGFT,8.880000,2022-01-11T23:52:15.000Z,8.840010,2022-02-11T23:50:49.000Z,-0.039990
DOGE,0.861920,2022-01-11T23:52:50.000Z,0.773850,2022-02-11T23:51:39.000Z,-0.088070
XRP,4.340020,2022-01-11T23:54:11.000Z,4.110150,2022-02-11T23:59:13.000Z,-0.229870
DAI,5.608520,2022-01-11T23:52:43.000Z,5.289110,2022-02-11T23:51:36.000Z,-0.319410
USDC,5.620520,2022-01-11T23:53:55.000Z,5.296160,2022-02-11T23:58:55.000Z,-0.324360
GALOFT,4.500000,2022-01-11T23:53:05.000Z,3.739980,2022-02-11T23:52:06.000Z,-0.760020
SCCPFT,4.650000,2022-01-11T23:53:41.000Z,3.870050,2022-02-11T23:57:36.000Z,-0.779950
MANA,16.499820,2022-01-11T23:53:25.000Z,15.718490,2022-02-11T23:54:20.000Z,-0.781330
ADA,6.749750,2022-01-11T23:52:09.000Z,5.795710,2022-02-11T23:59:27.000Z,-0.954040
GRT,3.219260,2022-01-11T23:53:07.000Z,2.236390,2022-02-11T23:52:19.000Z,-0.982870
SPFCFT,4.379930,2022-01-11T23:53:47.000Z,3.210000,2022-02-11T23:58:02.000Z,-1.169930
MENGOFT,7.392840,2022-01-11T23:53:33.000Z,5.890000,2022-02-11T23:54:53.000Z,-1.502840
AMFT,7.639890,2022-01-11T23:52:13.000Z,6.010000,2022-02-11T23:50:43.000Z,-1.629890
SAUBERFT,6.240560,2022-01-11T23:53:39.000Z,4.510000,2022-02-11T23:57:29.000Z,-1.730560
ALGO,8.249950,2022-01-11T23:52:11.000Z,4.999880,2022-02-11T23:59:36.000Z,-3.250070
ACMFT,27.494890,2022-01-11T23:52:07.000Z,23.989000,2022-02-11T23:59:26.000Z,-3.505890
CITYFT,59.749990,2022-01-11T23:52:39.000Z,55.959990,2022-02-11T23:51:30.000Z,-3.790000
MATIC,13.137290,2022-01-11T23:53:27.000Z,9.198530,2022-02-11T23:54:24.000Z,-3.938760
MBVASCO01,23.540100,2022-01-11T23:53:31.000Z,19.499800,2022-02-11T23:54:37.000Z,-4.040300
ASRFT,21.257320,2022-01-11T23:52:17.000Z,16.410050,2022-02-11T23:51:05.000Z,-4.847270
BARFT,44.000150,2022-01-11T23:52:25.000Z,33.110000,2022-02-11T23:51:18.000Z,-10.890150
JUVFT,45.921320,2022-01-11T23:53:15.000Z,34.920000,2022-02-11T23:52:29.000Z,-11.001320
UNI,90.697410,2022-01-11T23:53:53.000Z,57.842600,2022-02-11T23:58:53.000Z,-32.854810
AVAX,504.757420,2022-01-11T23:52:21.000Z,470.000000,2022-02-11T23:51:15.000Z,-34.757420
DOT,144.880000,2022-01-11T23:52:50.000Z,102.797010,2022-02-11T23:51:41.000Z,-42.082990
FIL,162.780000,2022-01-11T23:52:57.000Z,113.293480,2022-02-11T23:51:58.000Z,-49.486520
LINK,149.364750,2022-01-11T23:53:19.000Z,86.280000,2022-02-11T23:53:07.000Z,-63.084750
ICP,190.000000,2022-01-11T23:53:13.000Z,109.000000,2022-02-11T23:52:20.000Z,-81.000000
LTC,740.541540,2022-01-11T23:53:21.000Z,659.510170,2022-02-11T23:54:11.000Z,-81.031370
ATOM,227.500000,2022-01-11T23:52:19.000Z,143.409780,2022-02-11T23:51:13.000Z,-84.090220
AXS,410.616840,2022-01-11T23:52:23.000Z,314.150090,2022-02-11T23:51:15.000Z,-96.466750
SOL,792.069990,2022-01-11T23:53:45.000Z,520.652000,2022-02-11T23:57:48.000Z,-271.417990
AAVE,1221.889870,2022-01-11T23:52:06.000Z,880.307990,2022-02-11T23:59:26.000Z,-341.581880
BCH,2083.929870,2022-01-11T23:52:27.000Z,1706.120000,2022-02-11T23:51:19.000Z,-377.809870
ETH,18206.990000,2022-01-11T23:52:56.000Z,15606.596710,2022-02-11T23:51:55.000Z,-2600.393290
WBTC,236000.115150,2022-01-11T23:54:03.000Z,225000.060000,2022-02-11T23:59:06.000Z,-11000.055150
BTC,239165.143710,2022-01-11T23:52:31.000Z,224301.000000,2022-02-11T23:51:22.000Z,-14864.143710